apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: rakulrs/frontend-ca2:SHORT_SHA
          ports:
            - containerPort: 3000
          env:
            - name: NODE_ENV
              value: "development"
            - name: BACKEND_HOST
              value: "backend-service"
            - name: BACKEND_PORT
              value: "8080"
