name: Deploy backend to GKE

on:
  push:
    branches: 
      - main
    paths:
      - 'backend-ca2/**'
      - 'k8s/**'
      - '.github/workflows/**'
  pull_request:
    branches: 
      - main
    paths:
      - 'backend-ca2/**'
      - '.github/workflows/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'zulu'

      - name: Build with Maven
        working-directory: ./backend-ca2
        run: mvn clean install -DskipTests

      - name: Set Docker image name and commit SHA
        run: |
          echo "IMAGE_NAME=rakulrs/backend-ca2" >> $GITHUB_ENV
          echo "SHORT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
          echo "Full image name is: rakulrs/backend-ca2:${{ env.SHORT_SHA }}"

      - name: Build Docker image
        working-directory: ./backend-ca2
        run: |
          docker build -t ${{ env.IMAGE_NAME }}:${{ env.SHORT_SHA }} .

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image
        run: |
          docker push ${{ env.IMAGE_NAME }}:${{ env.SHORT_SHA }}

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          install_components: 'gke-gcloud-auth-plugin'

      - name: Configure kubeconfig for GKE
        run: |
          gcloud container clusters get-credentials ${{ secrets.GKE_CLUSTER_NAME }} \
            --zone ${{ secrets.GKE_CLUSTER_ZONE }} \
            --project ${{ secrets.GCP_PROJECT_ID }}

      - name: Deploy to Kubernetes
        run: |
          envsubst < k8s/applications/backend/be-deployment.yml | kubectl apply -f -